name: CI/CD Pipeline
on:
  push:
    branches: [ "main","develop" ]
  pull_request:
    branches: [ "main","develop" ]

      # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  test: 

    runs-on: ubuntu-latest
    env:
      HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
      HF_REPO_ID: ${{ secrets.HF_REPO_ID }}
      APP_ENV: production  # On force 'production' pour utiliser SQLite pendant les tests CI
      DATABASE_URL: sqlite:///./test_db.db
    steps:

      - name: check out du code
        uses: actions/checkout@v4

      - name: configuration de python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      
      - name: Installer uv et les dépendances
        run: |
          pip install uv
          uv sync --frozen --extra dev

      - name: Lancer les tests avec couverture
        run: uv run pytest --maxfail=1 --disable-warnings -q --cov=. --cov-report=html

      - name: Upload du rapport HTML comme artefact
        uses: actions/upload-artifact@v4
        with:
          name: rapport-couverture-html
          path: htmlcov/  

  deploiement:
    needs: test
    
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: déploiement sur HuggingFace
        env: 
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
          HF_REPO_ID: ${{ secrets.HF_REPO_ID }}
  
        run: |
          pip install huggingface_hub
          echo "Connexion à Hugging Face..."
          hf auth login --token $HUGGINGFACE_TOKEN
          echo "Déploiement du Space Prêt à dépenser"
          hf upload --repo-type space RandomFab/pret-a-depenser .

      


